[package]
name = "lib-server"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = []
embedded-server = [
    "dep:zksync_os_server",
    "dep:zksync_os_state_full_diffs",
    "dep:reth-tasks",
    "dep:smart-config",
]

[dependencies]
alloy = { workspace = true, features = ["provider-http", "reqwest", "eips"] }
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

zksync_os_server = { workspace = true, optional = true }
zksync_os_state_full_diffs = { workspace = true, optional = true }
reth-tasks = { workspace = true, optional = true }
smart-config = { workspace = true, optional = true }
