//! Artifact-sourced atomic-interop bindings.
//!
//! At build time this resolves the era-contracts checkout (the same resolver the deployer and the
//! integration tests use — `PROTOCOL_CONTRACTS_ROOT` if set, else the git checkout that
//! `protocol_ops` was compiled from) and reads the committed `l1-contracts/zkstack-out` ABIs for the
//! drift-critical atomic-interop contracts. It emits `$OUT_DIR/atomic_bindings.rs`, a set of
//! `alloy::sol!` invocations whose ABI JSON is embedded inline as a string literal.
//!
//! Sourcing from `zkstack-out` (rather than the gitignored forge `out/`) means the ABIs are present
//! at *compile* time on a clean checkout without a prior `forge build`, and CI keeps `zkstack-out`
//! in sync with the contracts — so a contract-shape change turns the crate red at build time instead
//! of drifting silently. Because the ABI JSON is embedded into the generated file, any shape change
//! changes the generated bytes and forces recompilation (a plain `sol!(_, "path")` would not, since
//! rustc does not fingerprint proc-macro file reads).

use std::fmt::Write as _;
use std::path::PathBuf;

/// `(solidity file stem, contract name)` for the drift-critical shapes. Their referenced structs
/// (`InteropBundle`, `AtomicFinalityProof`, `AtomicFlow`, `ImtProof`, `IMTLeaf`, the ERC-7786
/// attribute calls, …) are generated from these ABIs, so they are drift-checked for free.
const CONTRACTS: &[(&str, &str)] = &[
    ("InteropCenter", "InteropCenter"),
    ("L2InteropHandler", "L2InteropHandler"),
    ("AtomicFlowManager", "AtomicFlowManager"),
    ("L2NativeTokenVault", "L2NativeTokenVault"),
    ("IERC7786Attributes", "IERC7786Attributes"),
];

fn main() {
    let root = protocol_ops::common::paths::contracts_root();
    let zkstack_out = root.join("l1-contracts").join("zkstack-out");

    let mut generated = String::from(
        "// @generated by build.rs from committed zkstack-out ABIs — DO NOT EDIT.\n\
         // Regenerated automatically whenever the source ABIs change.\n",
    );

    for (file, name) in CONTRACTS {
        let src = zkstack_out
            .join(format!("{file}.sol"))
            .join(format!("{name}.json"));
        // Re-run if the ABI (or the era-contracts root override) changes.
        println!("cargo:rerun-if-changed={}", src.display());

        let abi = std::fs::read_to_string(&src).unwrap_or_else(|e| {
            panic!(
                "atomic-swap bindings: failed to read {src} ({e}).\n\
                 Expected committed zkstack-out ABIs under the era-contracts checkout at {root}.\n\
                 Set PROTOCOL_CONTRACTS_ROOT to a checkout whose l1-contracts/zkstack-out is built \
                 (CI keeps these in sync; locally: cd l1-contracts && forge build && yarn copy-to-zkstack-out.ts).",
                src = src.display(),
                root = root.display(),
            )
        });
        let abi = abi.trim();
        // zkstack-out stores bare ABI arrays; alloy's `sol!` parses a literal that starts with '['
        // as inline JSON (no file path). Guard the invariants we rely on.
        assert!(
            abi.starts_with('[') && abi.ends_with(']'),
            "expected a bare ABI array in {}, got a {}...",
            src.display(),
            &abi[..abi.len().min(40)]
        );
        assert!(
            !abi.contains("\"####"),
            "ABI JSON in {} contains the raw-string terminator sequence; bump the delimiter",
            src.display()
        );

        writeln!(
            generated,
            "alloy::sol!(\n    #[sol(rpc)]\n    #[allow(missing_docs, clippy::too_many_arguments)]\n    {name},\n    r####\"{abi}\"####\n);",
        )
        .unwrap();
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = PathBuf::from(out_dir).join("atomic_bindings.rs");
    std::fs::write(&dest, generated).expect("write atomic_bindings.rs");

    println!("cargo:rerun-if-env-changed=PROTOCOL_CONTRACTS_ROOT");
    println!("cargo:rerun-if-changed=build.rs");
}
