//! Shared engine for the end-to-end atomic-interop swap between two L1-settling ZKsync OS chains
//! (no gateway in the path), driven natively in Rust.
//!
//! One implementation, two callers:
//!   * the `atomic_swap_l1_settled` integration test (`tests/tests/atomic_swap.rs`) brings up the
//!     `ecosystem` fixture (two chains on one Anvil L1) and calls [`run_atomic_swap`];
//!   * the `atomic-swap-demo` binary (`tests/src/bin/atomic-swap-demo.rs`) reads RPCs/keys from the
//!     environment and calls the same [`run_atomic_swap`] against an already-running preset.
//!
//! The flow (bundle-model atomic swap):
//!   1. deploy + register a throwaway ERC-20 on each chain (mint to the user, approve the NTV),
//!   2. ensure the two chains are registered with each other for interop (permissionless
//!      `registerChain`; a no-op if the preset already did it at genesis),
//!   3. atomic-send both legs (burn + IMT insert), with the send-time low-nullifier index supplied
//!      by the server's Rust IMT engine (`zks_getImtLowNullifierIndex`),
//!   4. wait for each leg's commitment-tree root to settle on L1, fetch the real message proof
//!      (`zks_getL2ToL1LogProof`, messageRoot target) plus the IMT inclusion proof
//!      (`zks_getImtInclusionProof`), and wait for the L1 interop root to be imported on both chains,
//!   5. call `L2InteropHandler.executeAtomicBundle` per leg and assert both destination mints land
//!      (exact delta) and both bundles report `FullyExecuted`.
//!
//! ── Contract shapes are ARTIFACT-SOURCED ──────────────────────────────────────────────────────
//! The drift-critical protocol bindings (`InteropCenter`, `L2InteropHandler`, `AtomicFlowManager`,
//! `L2NativeTokenVault`, `IERC7786Attributes` — and every struct they reference) are generated by
//! `build.rs` from the committed `zkstack-out` ABIs of the resolved era-contracts checkout. A
//! contract-shape change fails this crate to COMPILE instead of drifting silently. The remaining
//! bindings below are stable, non-drift-prone views (a plain ERC-20, the L1/L2 bridgehub registration
//! surface, the interop-root storage view) and are declared inline.
#![allow(clippy::too_many_arguments)]

use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};

use alloy::network::{EthereumWallet, TransactionBuilder};
use alloy::primitives::{address, keccak256, Address, Bytes, FixedBytes, B256, U256};
use alloy::providers::{DynProvider, Provider, ProviderBuilder};
use alloy::rpc::types::TransactionRequest;
use alloy::signers::local::PrivateKeySigner;
use alloy::sol;
use alloy::sol_types::{SolCall, SolEvent, SolValue};
use anyhow::{bail, ensure, Context, Result};
use serde::Deserialize;
use tokio::time::sleep;

// Artifact-sourced protocol bindings: `InteropCenter`, `L2InteropHandler`, `AtomicFlowManager`,
// `L2NativeTokenVault`, `IERC7786Attributes`. Generated by build.rs from committed zkstack-out ABIs.
include!(concat!(env!("OUT_DIR"), "/atomic_bindings.rs"));

sol! {
    // ── Stable, non-drift-prone views declared inline ──
    #[sol(rpc)]
    interface ITestnetERC20 {
        function mint(address to, uint256 amount) external;
        function approve(address spender, uint256 amount) external returns (bool);
        function balanceOf(address account) external view returns (uint256);
    }
    #[sol(rpc)]
    interface IL2Bridgehub {
        function baseTokenAssetId(uint256 chainId) external view returns (bytes32);
    }
    #[sol(rpc)]
    interface IL1Bridgehub {
        function chainRegistrationSender() external view returns (address);
    }
    #[sol(rpc)]
    interface IChainRegistrationSender {
        function registerChain(uint256 chainToBeRegistered, uint256 chainRegisteredOn) external;
    }
    #[sol(rpc)]
    interface IL2InteropRootStorage {
        function interopRoots(uint256 chainId, uint256 blockOrBatchNumber) external view returns (bytes32);
    }
    #[sol(rpc)]
    interface IL2InteropCommitmentTree {
        function root() external view returns (bytes32);
        function leafCount() external view returns (uint256);
    }
}

// ── Fixed L2 built-in addresses (mirror contracts/common/l2-helpers/L2ContractAddresses.sol) ──
const NATIVE_TOKEN_VAULT: Address = address!("0000000000000000000000000000000000010004");
const ASSET_ROUTER: Address = address!("0000000000000000000000000000000000010003");
const INTEROP_ROOT_STORAGE: Address = address!("0000000000000000000000000000000000010008");
const L2_BRIDGEHUB: Address = address!("0000000000000000000000000000000000010002");

// ── Canonical atomic-interop layout (mirror L2ContractAddresses.sol) ──
const CANONICAL_INTEROP_CENTER: Address = address!("000000000000000000000000000000000001000d");
const CANONICAL_INTEROP_HANDLER: Address = address!("000000000000000000000000000000000001000e");
const CANONICAL_COMMITMENT_TREE: Address = address!("0000000000000000000000000000000000010012");
const CANONICAL_FLOW_MANAGER: Address = address!("0000000000000000000000000000000000010014");

/// Standard Anvil account #0 — funded on the harness L1; `registerChain` is permissionless.
const ANVIL_KEY0: &str = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";

const TOKEN_DECIMALS: u32 = 18;
/// Default flow deadline, as an L1 settlement-layer **timestamp** (unix seconds). The atomic-interop
/// l1-timestamp feature binds each settled batch's `block.timestamp` into its leaf and rejects a leg
/// whose batch settled after the deadline, so this must sit comfortably above the batches' real
/// settlement timestamps — far in the future here (year ~2286).
pub const DEFAULT_DEADLINE: u64 = 10_000_000_000;
const ATOMIC_SEND_GAS: u64 = 3_000_000;
const TX_GAS: u64 = 5_000_000;

/// `LegState.Committed` (IAtomicInterop.sol).
const LEG_COMMITTED: u8 = 1;
/// `BundleStatus.FullyExecuted` (common/Messaging.sol).
const BUNDLE_FULLY_EXECUTED: u8 = 2;

/// Env-overridable addresses of the atomic contracts.
#[derive(Clone, Copy, Debug)]
pub struct Layout {
    pub interop_center: Address,
    pub interop_handler: Address,
    pub commitment_tree: Address,
    pub flow_manager: Address,
}

impl Default for Layout {
    fn default() -> Self {
        Self {
            interop_center: CANONICAL_INTEROP_CENTER,
            interop_handler: CANONICAL_INTEROP_HANDLER,
            commitment_tree: CANONICAL_COMMITMENT_TREE,
            flow_manager: CANONICAL_FLOW_MANAGER,
        }
    }
}

/// Inputs for one end-to-end atomic swap between chain A and chain B.
pub struct AtomicSwapParams {
    /// L2 RPC URL of chain A.
    pub rpc_a: String,
    /// L2 RPC URL of chain B.
    pub rpc_b: String,
    /// L1 (settlement layer) RPC URL — its chain id is folded into the flowId, and it hosts the
    /// permissionless chain-registration sender.
    pub l1_rpc: String,
    /// Depositor / recipient wallet (must be funded on both chains).
    pub signer: PrivateKeySigner,
    /// Amount chain A sends to the user on chain B.
    pub a_amount: U256,
    /// Amount chain B sends to the user on chain A.
    pub b_amount: U256,
    /// Amount minted to the depositor on each throwaway token (also the NTV approval amount).
    pub supply: U256,
    /// Flow deadline as an L1 settlement-layer timestamp (see [`DEFAULT_DEADLINE`]).
    pub deadline: u64,
    /// era-contracts checkout root, used to read the `TestnetERC20Token` creation bytecode from its
    /// forge `out/` (resolve with `protocol_ops::common::paths::contracts_root()`).
    pub era_root: PathBuf,
    /// L1 Bridgehub, used to resolve the chain-registration sender when the chains are not yet
    /// registered with each other. `None` requires the chains to be pre-registered (e.g. a preset
    /// that registers at genesis); registration is then skipped.
    pub bridgehub: Option<Address>,
    /// Atomic-interop contract layout.
    pub layout: Layout,
}

/// Per-chain context: a label, a wallet-bound L2 provider, the chain id, and its deployed test token.
struct ChainCtx {
    name: &'static str,
    chain_id: u64,
    provider: DynProvider,
    token: Address,
}

// ── RPC response shapes (zks_* extensions) ──
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RawLogProof {
    batch_number: Option<u64>,
    id: u64,
    proof: Vec<B256>,
    gateway_block_number: Option<u64>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RpcImtLeaf {
    value: U256,
    next_index: U256,
    next_value: U256,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RpcImtProof {
    chain_imt_root: B256,
    leaf: RpcImtLeaf,
    imt_leaf_index: u64,
    imt_proof: Vec<B256>,
}

/// `keccak256(abi.encode(uint256 chainId, address NTV, address token))` — mirrors `DataEncoding.encodeNTVAssetId`.
fn ntv_asset_id(chain_id: u64, token: Address) -> B256 {
    keccak256((U256::from(chain_id), NATIVE_TOKEN_VAULT, token).abi_encode_params())
}

/// ERC-7930 EVM chain reference without an address component.
fn encode_evm_chain(chain_id: u64) -> Bytes {
    let be = chain_id.to_be_bytes();
    let first = be.iter().position(|&b| b != 0).unwrap_or(be.len() - 1);
    let chain_ref = &be[first..];
    let mut out = vec![0x00, 0x01, 0x00, 0x00, chain_ref.len() as u8];
    out.extend_from_slice(chain_ref);
    out.push(0x00);
    Bytes::from(out)
}

/// ERC-7930 EVM address without a chain reference.
fn encode_evm_address(addr: Address) -> Bytes {
    let mut out = vec![0x00, 0x01, 0x00, 0x00, 0x00, 0x14];
    out.extend_from_slice(addr.as_slice());
    Bytes::from(out)
}

/// `secondBridgeData` for an ERC20 transfer via the L2 asset router: `0x01 ++ abi.encode(bytes32 assetId, bytes burnData)`
/// where `burnData = abi.encode(uint256 amount, address receiver, address(0))`.
fn token_transfer_data(asset_id: B256, amount: U256, recipient: Address) -> Bytes {
    let burn_data = (amount, recipient, Address::ZERO).abi_encode_params();
    let mut out = vec![0x01u8];
    out.extend_from_slice(&(asset_id, Bytes::from(burn_data)).abi_encode_params());
    Bytes::from(out)
}

/// Indirect-call ERC-7786 attribute with zero call value.
fn indirect_call_attr() -> Bytes {
    Bytes::from(
        IERC7786Attributes::indirectCallCall {
            _indirectCallMessageValue: U256::ZERO,
        }
        .abi_encode(),
    )
}

/// `atomicBundle` ERC-7786 attribute carrying the out-of-band atomic params.
fn atomic_bundle_attr(flow_id: B256, deadline: u64, low_nullifier_index: U256) -> Bytes {
    Bytes::from(
        IERC7786Attributes::atomicBundleCall {
            _flowId: flow_id,
            _deadline: deadline,
            _lowNullifierIndex: low_nullifier_index,
        }
        .abi_encode(),
    )
}

/// `interopBundleSalt` ERC-7786 attribute. The InteropCenter folds `keccak256(msg.sender, salt)` into
/// the bundle hash and rejects a reused `(sender, salt)` pair, so every leg needs a distinct salt.
fn interop_bundle_salt_attr(salt: B256) -> Bytes {
    Bytes::from(IERC7786Attributes::interopBundleSaltCall { _salt: salt }.abi_encode())
}

/// The bridge call-starter that burns `amount` of `source`'s token and mints it to `recipient` on the destination.
fn bridge_call_starter(
    source: &ChainCtx,
    amount: U256,
    recipient: Address,
) -> InteropCenter::InteropCallStarter {
    InteropCenter::InteropCallStarter {
        to: encode_evm_address(ASSET_ROUTER),
        data: token_transfer_data(
            ntv_asset_id(source.chain_id, source.token),
            amount,
            recipient,
        ),
        callAttributes: vec![indirect_call_attr()],
    }
}

/// `flowId = keccak256(abi.encode(bytes32[] legBundleHashes, uint256[] legSourceChainIds, uint64 deadline, uint256 settlementLayerChainId))` (both arrays ascending).
fn compute_flow_id(
    leg_hashes_asc: &[B256],
    chain_ids_asc: &[U256],
    deadline: u64,
    settlement_layer_chain_id: U256,
) -> B256 {
    keccak256(
        (
            leg_hashes_asc.to_vec(),
            chain_ids_asc.to_vec(),
            deadline,
            settlement_layer_chain_id,
        )
            .abi_encode_params(),
    )
}

/// `commitValue = keccak256(abi.encode(bytes4 ATOMIC_COMMIT_LEAF_TAG, bytes32 flowId, bytes32 bundleHash))` as uint256.
fn commit_value(flow_id: B256, bundle_hash: B256) -> U256 {
    let tag = FixedBytes::<4>::from_slice(&keccak256(b"AtomicInterop.commit.v1")[..4]);
    U256::from_be_bytes(keccak256((tag, flow_id, bundle_hash).abi_encode_params()).0)
}

/// Build a wallet-bound L2 provider for `signer`.
async fn l2_provider(rpc: &str, signer: PrivateKeySigner) -> Result<DynProvider> {
    Ok(ProviderBuilder::new()
        .wallet(EthereumWallet::from(signer))
        .connect(rpc)
        .await
        .with_context(|| format!("connect L2 {rpc}"))?
        .erased())
}

/// Deploy a fresh TestnetERC20Token (creation bytecode from the era-contracts forge `out/`), returning its address.
async fn deploy_token(provider: &DynProvider, era_root: &Path) -> Result<Address> {
    let artifact_path =
        era_root.join("l1-contracts/out/TestnetERC20Token.sol/TestnetERC20Token.json");
    let json: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(&artifact_path)
            .with_context(|| format!("read token artifact {}", artifact_path.display()))?,
    )?;
    let bytecode_hex = json["bytecode"]["object"]
        .as_str()
        .context("token artifact missing bytecode.object")?;
    let mut init =
        hex::decode(bytecode_hex.trim_start_matches("0x")).context("decode token bytecode")?;
    init.extend_from_slice(
        &(
            "AtomicTest".to_string(),
            "ATT".to_string(),
            U256::from(TOKEN_DECIMALS),
        )
            .abi_encode_params(),
    );
    let tx = TransactionRequest::default()
        .with_deploy_code(init)
        .with_gas_limit(TX_GAS);
    let receipt = provider.send_transaction(tx).await?.get_receipt().await?;
    ensure!(receipt.status(), "token deploy reverted");
    receipt
        .contract_address
        .context("no contract address in deploy receipt")
}

/// Deploy + mint + register-with-NTV + approve a test token for `signer` on the chain at `rpc`.
async fn setup_token(
    name: &'static str,
    rpc: &str,
    signer: PrivateKeySigner,
    mint: U256,
    era_root: &Path,
) -> Result<ChainCtx> {
    let provider = l2_provider(rpc, signer.clone()).await?;
    let user = signer.address();
    let chain_id = provider.get_chain_id().await?;
    let token = deploy_token(&provider, era_root).await?;

    let erc20 = ITestnetERC20::new(token, &provider);
    let r = erc20
        .mint(user, mint)
        .gas(TX_GAS)
        .send()
        .await?
        .get_receipt()
        .await?;
    ensure!(r.status(), "mint reverted");

    let ntv = L2NativeTokenVault::new(NATIVE_TOKEN_VAULT, &provider);
    if ntv.assetId(token).call().await? == B256::ZERO {
        let r = ntv
            .registerToken(token)
            .gas(TX_GAS)
            .send()
            .await?
            .get_receipt()
            .await?;
        ensure!(r.status(), "registerToken reverted");
    }
    let r = erc20
        .approve(NATIVE_TOKEN_VAULT, mint)
        .gas(TX_GAS)
        .send()
        .await?
        .get_receipt()
        .await?;
    ensure!(r.status(), "approve reverted");
    println!("[{name}] chain {chain_id}: token {token} deployed / minted / registered / approved");
    Ok(ChainCtx {
        name,
        chain_id,
        provider,
        token,
    })
}

/// Capability gate: the commitment tree must be deployed and behave like the atomic built-in. Exposed
/// for the standalone demo binary, which runs against an image it does not itself provision.
pub async fn assert_atomic_capable(
    name: &str,
    provider: &DynProvider,
    layout: &Layout,
) -> Result<()> {
    let code = provider.get_code_at(layout.commitment_tree).await?;
    if code.is_empty() {
        bail!(
            "BLOCKED: chain {name} has no L2InteropCommitmentTree at {} — needs an atomic-capable \
             zksync-os-server image + an atomic-interop genesis (atomic-imt-interop-release).",
            layout.commitment_tree
        );
    }
    let tree = IL2InteropCommitmentTree::new(layout.commitment_tree, provider);
    tree.root()
        .call()
        .await
        .context("commitment tree root() reverted — contract at that address is not the IMT")?;
    tree.leafCount()
        .call()
        .await
        .context("commitment tree leafCount() reverted")?;
    Ok(())
}

/// Ensure A and B are registered with each other for interop. No-op if both already know each other
/// (e.g. a preset registered them at genesis); otherwise resolves the permissionless chain-registration
/// sender on L1 (`bridgehub` required) and registers the missing directions, polling until they land.
async fn ensure_chains_registered(
    l1_rpc: &str,
    bridgehub: Option<Address>,
    a: &ChainCtx,
    b: &ChainCtx,
) -> Result<()> {
    let a_knows_b = IL2Bridgehub::new(L2_BRIDGEHUB, &a.provider)
        .baseTokenAssetId(U256::from(b.chain_id))
        .call()
        .await?
        != B256::ZERO;
    let b_knows_a = IL2Bridgehub::new(L2_BRIDGEHUB, &b.provider)
        .baseTokenAssetId(U256::from(a.chain_id))
        .call()
        .await?
        != B256::ZERO;
    if a_knows_b && b_knows_a {
        println!("[atomic-swap] chains already registered for interop");
        return Ok(());
    }

    let bridgehub = bridgehub.context(
        "chains are not registered with each other and no L1 bridgehub was provided to register them",
    )?;
    let l1_signer: PrivateKeySigner = ANVIL_KEY0.parse()?;
    let l1 = ProviderBuilder::new()
        .wallet(EthereumWallet::from(l1_signer))
        .connect(l1_rpc)
        .await?
        .erased();
    let sender_addr = IL1Bridgehub::new(bridgehub, &l1)
        .chainRegistrationSender()
        .call()
        .await?;
    let sender = IChainRegistrationSender::new(sender_addr, &l1);
    println!("[atomic-swap] chainRegistrationSender = {sender_addr}");

    // A must learn B (registerChain(B, A)) and vice versa.
    for (to_register, registered_on) in [(b, a), (a, b)] {
        let l2bh = IL2Bridgehub::new(L2_BRIDGEHUB, &registered_on.provider);
        if l2bh
            .baseTokenAssetId(U256::from(to_register.chain_id))
            .call()
            .await?
            != B256::ZERO
        {
            continue;
        }
        let r = sender
            .registerChain(
                U256::from(to_register.chain_id),
                U256::from(registered_on.chain_id),
            )
            .gas(TX_GAS)
            .send()
            .await?
            .get_receipt()
            .await?;
        ensure!(r.status(), "registerChain reverted");
        // Poll until the L2 service tx lands and sets the base-token asset id.
        let start = Instant::now();
        loop {
            if l2bh
                .baseTokenAssetId(U256::from(to_register.chain_id))
                .call()
                .await?
                != B256::ZERO
            {
                break;
            }
            ensure!(
                start.elapsed() < Duration::from_secs(120),
                "chain {} never learned chain {}'s base token",
                registered_on.chain_id,
                to_register.chain_id
            );
            sleep(Duration::from_secs(1)).await;
        }
        println!(
            "[atomic-swap] chain {} now knows {}",
            registered_on.chain_id, to_register.chain_id
        );
    }
    Ok(())
}

/// Predict a leg's bundleHash via an atomic `sendBundle` callStatic (bundleHash is independent of the atomic params).
async fn predict_bundle_hash(
    source: &ChainCtx,
    dest: &ChainCtx,
    amount: U256,
    recipient: Address,
    interop_center: Address,
    fee: U256,
    deadline: u64,
    salt: B256,
) -> Result<B256> {
    InteropCenter::new(interop_center, &source.provider)
        .sendBundle(
            encode_evm_chain(dest.chain_id),
            vec![bridge_call_starter(source, amount, recipient)],
            // Same salt as `send_atomic_leg` so the predicted hash matches the emitted one.
            vec![
                atomic_bundle_attr(B256::ZERO, deadline, U256::ZERO),
                interop_bundle_salt_attr(salt),
            ],
        )
        .value(fee)
        .gas(ATOMIC_SEND_GAS)
        .call()
        .await
        .context("predict sendBundle callStatic")
}

/// Atomic-send one leg (burn + IMT insert). Returns `(bundleData, bundleHash, txHash, sendBlock)`.
async fn send_atomic_leg(
    source: &ChainCtx,
    dest: &ChainCtx,
    amount: U256,
    recipient: Address,
    flow_id: B256,
    predicted_hash: B256,
    interop_center: Address,
    fee: U256,
    deadline: u64,
    salt: B256,
) -> Result<(Bytes, B256, B256, u64)> {
    let value = commit_value(flow_id, predicted_hash);
    // Low-nullifier (predecessor) index from the server's Rust IMT engine against the pre-insert tree.
    let block = source.provider.get_block_number().await?;
    let low_null: Option<u64> = source
        .provider
        .raw_request("zks_getImtLowNullifierIndex".into(), (value, block))
        .await
        .context("zks_getImtLowNullifierIndex")?;
    let low_null = low_null.context("no low-nullifier leaf for commit value")?;

    let ic = InteropCenter::new(interop_center, &source.provider);
    let receipt = ic
        .sendBundle(
            encode_evm_chain(dest.chain_id),
            vec![bridge_call_starter(source, amount, recipient)],
            vec![
                atomic_bundle_attr(flow_id, deadline, U256::from(low_null)),
                interop_bundle_salt_attr(salt),
            ],
        )
        .value(fee)
        .gas(ATOMIC_SEND_GAS)
        .send()
        .await?
        .get_receipt()
        .await?;
    ensure!(receipt.status(), "atomic sendBundle reverted");
    let tx_hash = receipt.transaction_hash;

    // Extract the InteropBundleSent event: bundleHash + the bundle struct (re-encoded as bundleData).
    let mut found: Option<(B256, Bytes)> = None;
    for log in receipt.inner.logs() {
        if log.address() != interop_center {
            continue;
        }
        if let Ok(decoded) = InteropCenter::InteropBundleSent::decode_log(&log.inner) {
            found = Some((
                decoded.interopBundleHash,
                Bytes::from(decoded.interopBundle.abi_encode()),
            ));
            break;
        }
    }
    let (bundle_hash, bundle_data) = found.context("InteropBundleSent event not found")?;
    ensure!(
        bundle_hash == predicted_hash,
        "predicted bundleHash {predicted_hash} != emitted {bundle_hash}"
    );
    let send_block = receipt.block_number.context("send block number")?;
    println!(
        "[{}->{}] atomic leg sent, bundleHash={bundle_hash} lowNullifier={low_null}",
        source.name, dest.name
    );
    Ok((bundle_data, bundle_hash, tx_hash, send_block))
}

/// Index of the commitment-tree L2->L1 message within the tx (scan by sender; 0 fallback).
async fn commitment_tree_message_index(
    provider: &DynProvider,
    tx_hash: B256,
    commitment_tree: Address,
) -> Result<u64> {
    let receipt: serde_json::Value = provider
        .raw_request("eth_getTransactionReceipt".into(), (tx_hash,))
        .await
        .context("eth_getTransactionReceipt (raw)")?;
    let tree = format!("{commitment_tree:#x}");
    if let Some(logs) = receipt["l2ToL1Logs"].as_array() {
        for (idx, l) in logs.iter().enumerate() {
            if l["sender"].as_str().unwrap_or("").to_lowercase() == tree {
                return Ok(idx as u64);
            }
        }
    }
    Ok(0)
}

/// Poll `zks_getL2ToL1LogProof` (messageRoot target) until the commitment-tree publish in `tx_hash` settles.
async fn wait_for_message_proof(
    provider: &DynProvider,
    tx_hash: B256,
    msg_index: u64,
) -> Result<RawLogProof> {
    let start = Instant::now();
    loop {
        let res: Option<RawLogProof> = provider
            .raw_request(
                "zks_getL2ToL1LogProof".into(),
                (tx_hash, msg_index, "messageRoot"),
            )
            .await
            .context("zks_getL2ToL1LogProof")?;
        if let Some(p) = res {
            return Ok(p);
        }
        ensure!(
            start.elapsed() < Duration::from_secs(300),
            "timed out waiting for message proof of {tx_hash}"
        );
        sleep(Duration::from_secs(2)).await;
    }
}

/// Build a leg's `ImtProof`: IMT half from the Rust engine RPC, message half from the real proof.
async fn build_inclusion_proof(
    source: &ChainCtx,
    value: U256,
    send_block: u64,
    raw: &RawLogProof,
) -> Result<L2InteropHandler::ImtProof> {
    let imt: Option<RpcImtProof> = source
        .provider
        .raw_request("zks_getImtInclusionProof".into(), (value, send_block))
        .await
        .context("zks_getImtInclusionProof")?;
    let imt = imt.context("commit value not present in IMT (server returned null)")?;
    Ok(L2InteropHandler::ImtProof {
        sourceChainId: U256::from(source.chain_id),
        batchNumber: U256::from(raw.batch_number.unwrap_or(0)),
        chainImtRoot: imt.chain_imt_root,
        messageTxNumberInBatch: 0,
        messageIndex: U256::from(raw.id),
        messageProof: raw.proof.clone(),
        leaf: L2InteropHandler::IMTLeaf {
            value: imt.leaf.value,
            nextIndex: imt.leaf.next_index,
            nextValue: imt.leaf.next_value,
        },
        imtLeafIndex: U256::from(imt.imt_leaf_index),
        imtProof: imt.imt_proof,
    })
}

/// Poll a chain's L2InteropRootStorage until it imports the interop root for `(l1_chain_id, sl_block)`.
async fn wait_for_interop_root(
    provider: &DynProvider,
    l1_chain_id: u64,
    sl_block: u64,
) -> Result<()> {
    let storage = IL2InteropRootStorage::new(INTEROP_ROOT_STORAGE, provider);
    let start = Instant::now();
    loop {
        if storage
            .interopRoots(U256::from(l1_chain_id), U256::from(sl_block))
            .call()
            .await?
            != B256::ZERO
        {
            return Ok(());
        }
        ensure!(
            start.elapsed() < Duration::from_secs(180),
            "chain never imported interop root (L1 {l1_chain_id}, block {sl_block})"
        );
        sleep(Duration::from_secs(2)).await;
    }
}

/// Balance of `holder` in the destination shim for `source`'s token, or zero if the shim does not
/// exist yet (it is created on first mint). Used to assert the exact minted delta.
async fn shim_balance(
    dest: &ChainCtx,
    source: &ChainCtx,
    holder: Address,
) -> Result<(Address, U256)> {
    let ntv = L2NativeTokenVault::new(NATIVE_TOKEN_VAULT, &dest.provider);
    let shim = ntv
        .tokenAddress(ntv_asset_id(source.chain_id, source.token))
        .call()
        .await?;
    if shim == Address::ZERO {
        return Ok((shim, U256::ZERO));
    }
    let bal = ITestnetERC20::new(shim, &dest.provider)
        .balanceOf(holder)
        .call()
        .await?;
    Ok((shim, bal))
}

/// Run the full end-to-end atomic swap between two L1-settling chains, asserting every relevant
/// side effect. Shared by the `atomic_swap_l1_settled` integration test and the `atomic-swap-demo`
/// binary.
pub async fn run_atomic_swap(p: AtomicSwapParams) -> Result<()> {
    let user = p.signer.address();

    println!("[atomic-swap] setting up tokens...");
    let a = setup_token("A", &p.rpc_a, p.signer.clone(), p.supply, &p.era_root).await?;
    let b = setup_token("B", &p.rpc_b, p.signer.clone(), p.supply, &p.era_root).await?;

    let fee = InteropCenter::new(p.layout.interop_center, &a.provider)
        .interopProtocolFee()
        .call()
        .await?;
    println!("[atomic-swap] interopProtocolFee (per call): {fee}");

    println!("[atomic-swap] ensuring chains are registered for interop...");
    ensure_chains_registered(&p.l1_rpc, p.bridgehub, &a, &b).await?;

    // ── Predict bundle hashes -> flowId ──
    // For L1-settling chains the atomic flow's settlement layer is L1 itself; its chain id is part of
    // the flowId preimage, so resolve it before computing the flowId.
    let l1 = ProviderBuilder::new().connect(&p.l1_rpc).await?.erased();
    let l1_chain_id = l1.get_chain_id().await?;
    // Each leg needs a distinct interop-bundle salt: the InteropCenter folds `keccak256(sender, salt)`
    // into the bundle hash and rejects a reused (sender, salt) pair. Legs settle on different chains,
    // so fixed per-leg salts are unique enough for the fresh test chains.
    let salt_ab = keccak256(b"atomic-swap-leg-ab");
    let salt_ba = keccak256(b"atomic-swap-leg-ba");
    let h_ab = predict_bundle_hash(
        &a,
        &b,
        p.a_amount,
        user,
        p.layout.interop_center,
        fee,
        p.deadline,
        salt_ab,
    )
    .await?;
    let h_ba = predict_bundle_hash(
        &b,
        &a,
        p.b_amount,
        user,
        p.layout.interop_center,
        fee,
        p.deadline,
        salt_ba,
    )
    .await?;
    let mut leg_hashes_asc = [h_ab, h_ba];
    leg_hashes_asc.sort();
    let mut chain_ids_asc = [U256::from(a.chain_id), U256::from(b.chain_id)];
    chain_ids_asc.sort();
    let flow_id = compute_flow_id(
        &leg_hashes_asc,
        &chain_ids_asc,
        p.deadline,
        U256::from(l1_chain_id),
    );
    println!(
        "[atomic-swap] flowId={flow_id} deadline={} settlementLayer(L1)={l1_chain_id}",
        p.deadline
    );

    // ── PHASE 1: atomic send both legs ──
    let a_token = ITestnetERC20::new(a.token, &a.provider);
    let b_token = ITestnetERC20::new(b.token, &b.provider);
    let a_before = a_token.balanceOf(user).call().await?;
    let b_before = b_token.balanceOf(user).call().await?;
    // Capture destination-shim balances before execution so we can assert the exact minted delta.
    let (_, a_on_b_before) = shim_balance(&b, &a, user).await?;
    let (_, b_on_a_before) = shim_balance(&a, &b, user).await?;

    let (ab_data, _ab_hash, ab_tx, ab_block) = send_atomic_leg(
        &a,
        &b,
        p.a_amount,
        user,
        flow_id,
        h_ab,
        p.layout.interop_center,
        fee,
        p.deadline,
        salt_ab,
    )
    .await?;
    let (ba_data, _ba_hash, ba_tx, ba_block) = send_atomic_leg(
        &b,
        &a,
        p.b_amount,
        user,
        flow_id,
        h_ba,
        p.layout.interop_center,
        fee,
        p.deadline,
        salt_ba,
    )
    .await?;

    let mgr_a = AtomicFlowManager::new(p.layout.flow_manager, &a.provider);
    let mgr_b = AtomicFlowManager::new(p.layout.flow_manager, &b.provider);
    ensure!(
        mgr_a.legState(flow_id, h_ab).call().await? == LEG_COMMITTED,
        "AB committed on A"
    );
    ensure!(
        mgr_b.legState(flow_id, h_ba).call().await? == LEG_COMMITTED,
        "BA committed on B"
    );
    ensure!(
        a_token.balanceOf(user).call().await? == a_before - p.a_amount,
        "A burned aAmount"
    );
    ensure!(
        b_token.balanceOf(user).call().await? == b_before - p.b_amount,
        "B burned bAmount"
    );
    println!("[atomic-swap] PHASE 1 ok: both legs committed (burn + IMT insert)");

    // ── PHASE 2: wait for L1 settlement, fetch real proofs, build inclusion proofs ──
    let ab_msg_idx =
        commitment_tree_message_index(&a.provider, ab_tx, p.layout.commitment_tree).await?;
    let ba_msg_idx =
        commitment_tree_message_index(&b.provider, ba_tx, p.layout.commitment_tree).await?;
    println!("[atomic-swap] waiting for commitment-tree roots to settle on L1...");
    let ab_raw = wait_for_message_proof(&a.provider, ab_tx, ab_msg_idx).await?;
    let ba_raw = wait_for_message_proof(&b.provider, ba_tx, ba_msg_idx).await?;
    println!(
        "[atomic-swap] AB proof: batch={:?} slBlock={:?}; BA proof: batch={:?} slBlock={:?}",
        ab_raw.batch_number,
        ab_raw.gateway_block_number,
        ba_raw.batch_number,
        ba_raw.gateway_block_number
    );

    let ab_proof =
        build_inclusion_proof(&a, commit_value(flow_id, h_ab), ab_block, &ab_raw).await?;
    let ba_proof =
        build_inclusion_proof(&b, commit_value(flow_id, h_ba), ba_block, &ba_raw).await?;
    // Proofs ordered to match legBundleHashes ascending.
    let proofs_asc = if h_ab < h_ba {
        vec![ab_proof, ba_proof]
    } else {
        vec![ba_proof, ab_proof]
    };
    let finality = L2InteropHandler::AtomicFinalityProof {
        flow: L2InteropHandler::AtomicFlow {
            flowId: flow_id,
            deadline: p.deadline,
            settlementLayerChainId: U256::from(l1_chain_id),
            legBundleHashes: leg_hashes_asc.to_vec(),
            legSourceChainIds: chain_ids_asc.to_vec(),
        },
        proofs: proofs_asc,
    };

    // Both executeAtomicBundle calls verify every leg, so each executing chain must have imported the
    // L1 interop root at each leg's settlement block.
    let sl_blocks: Vec<u64> = [ab_raw.gateway_block_number, ba_raw.gateway_block_number]
        .into_iter()
        .flatten()
        .collect();
    println!("[atomic-swap] waiting for interop roots (L1 {l1_chain_id}) at blocks {sl_blocks:?} on both chains...");
    for ctx in [&a, &b] {
        for &sl in &sl_blocks {
            wait_for_interop_root(&ctx.provider, l1_chain_id, sl).await?;
        }
    }
    println!("[atomic-swap] interop roots imported on both chains");

    // ── PHASE 3: executeAtomicBundle on each destination ──
    println!("[atomic-swap] executing AB on B and BA on A...");
    let handler_b = L2InteropHandler::new(p.layout.interop_handler, &b.provider);
    let handler_a = L2InteropHandler::new(p.layout.interop_handler, &a.provider);
    let r = handler_b
        .executeAtomicBundle(ab_data, finality.clone())
        .gas(TX_GAS)
        .send()
        .await?
        .get_receipt()
        .await?;
    ensure!(r.status(), "executeAtomicBundle AB on B succeeds");
    let r = handler_a
        .executeAtomicBundle(ba_data, finality)
        .gas(TX_GAS)
        .send()
        .await?
        .get_receipt()
        .await?;
    ensure!(r.status(), "executeAtomicBundle BA on A succeeds");
    ensure!(
        handler_b.bundleStatus(h_ab).call().await? == BUNDLE_FULLY_EXECUTED,
        "AB bundle FullyExecuted on B"
    );
    ensure!(
        handler_a.bundleStatus(h_ba).call().await? == BUNDLE_FULLY_EXECUTED,
        "BA bundle FullyExecuted on A"
    );

    // ── Destination mint assertions: each recipient's shim balance grew by exactly the sent amount ──
    let (shim_a_on_b, a_on_b_after) = shim_balance(&b, &a, user).await?;
    ensure!(shim_a_on_b != Address::ZERO, "shim for A's token on B");
    ensure!(
        a_on_b_after - a_on_b_before == p.a_amount,
        "recipient on B received exactly aAmount"
    );
    let (shim_b_on_a, b_on_a_after) = shim_balance(&a, &b, user).await?;
    ensure!(shim_b_on_a != Address::ZERO, "shim for B's token on A");
    ensure!(
        b_on_a_after - b_on_a_before == p.b_amount,
        "recipient on A received exactly bAmount"
    );

    println!("[atomic-swap] SUCCESS: atomic swap completed end-to-end on two L1-settling chains");
    Ok(())
}

/// One unit of the throwaway token (18 decimals), for callers computing amounts.
pub fn token_unit() -> U256 {
    U256::from(10u64).pow(U256::from(TOKEN_DECIMALS))
}
