name: CI

on:
  pull_request:
  push:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions:
  contents: read

jobs:

  build-format-lint:
    runs-on: matterlabs-ci-runner-high-performance
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup runner
        uses: ./.github/actions/runner-setup

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

      - name: Build
        run: cargo build --release --workspace

  ci-success:
    name: Github Status Check
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    needs: [build-format-lint]
    steps:
      - name: Status
        run: |
          if [[ "${{ contains(join(needs.*.result, ','), 'failure') }}" == "true" ]]; then
            echo "CI failed"
            exit 1
          fi
